// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bootShop.DataAccess.Data;

namespace bootShop.DataAccess.Migrations
{
    [DbContext(typeof(bootShopDbContext))]
    [Migration("20220416091944_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bootShop.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Telefon"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tablet"
                        });
                });

            modelBuilder.Entity("bootShop.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/189/222-222/110000155170720.jpg/format:webp",
                            Name = "IPhone",
                            Price = 1500.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/178/222-222/110000142772021.jpg/format:webp",
                            Name = "Samsung",
                            Price = 1500.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/50/222-222/11030233219122.jpg/format:webp",
                            Name = "Huawei",
                            Price = 1500.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/131/222-222/110000081537720.jpg/format:webp",
                            Name = "Macbook Pro",
                            Price = 1500.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/206/222-222/110000182816133.jpg/format:webp",
                            Name = "Lenovo",
                            Price = 1500.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Discount = 0.14999999999999999,
                            ImageUrl = "https://productimages.hepsiburada.net/s/153/222-222/110000109127071.jpg/format:webp",
                            Name = "Matebook",
                            Price = 1500.0
                        });
                });

            modelBuilder.Entity("bootShop.Entities.Product", b =>
                {
                    b.HasOne("bootShop.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("bootShop.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
